### ISSUE TITLE
Will pattern based or position based masking be supported?

### ISSUE THREAD

**Issue by cswhwang** [eBay/ejmask#10]
We'd like to have masking methods to mask sensitive data in random file formats such as TXT or CSV files.

**Comment by prasanthkv** [comment]
This library design to optimize regex patterns to mask string file or format does't matter.
Here is an example of how to configure patten for plain text.  

https://github.com/eBay/ejmask/blob/807eff8d1a84ba7213d3d1a5bf00c69fa56d0d03/ejmask-extensions/src/main/java/com/ebay/ejmask/extenstion/builder/header/HeaderFieldPatternBuilder.java#L26-L59

**Comment by prasanthkv** [comment]
@SteadyStill  if you have any specific use case in mind please elaborate with an example
