### ISSUE TITLE
Non String Values are not Masked

### ISSUE THREAD

**Issue by OmarAlJarrah** [eBay/ejmask#17]
## Issue Report
Using the `JsonFieldPatternBuilder`, the masker appears to only mask string values, while ignoring other non-string values (e.g. numbers, booleans, ...etc).

## Expected Behavior
```json
{"name": "omitted", "id": "omitted"}
```

## Actual Behavior
```json
{"name": "omitted", "id": 125}
```

## Steps to Reproduce the Issue
**Check the following piece of code:**
```kotlin
class SampleJsonFilter: BaseFilter(JsonFieldPatternBuilder::class.java,  *maskedFields) {
    override fun getPatternBuilder(): Class<out IPatternBuilder> = JsonMaskPatternBuilder::class.java

    override fun getFieldNames(): Array<String> = arrayOf("name", "id")
}

fun main() {
    var masked = ""
    json = "{ \"name\": "Linux", \"id\": 125 }"
    val maskingConfig = JsonMaskingConfig.builder()
        .maskKeys(maskedFields.toSet())
        .maskStringsWith("omitted")
        .build()

    val masker = JsonMasker.getMasker(maskingConfig)
    EJMaskInitializer.addFilter(SampleJsonFilter())
}
```

**Comment by prasanthkv** [comment]
Thanks @OmarAlJarrah for reporting this issue .. we are looking into this.

**Comment by RandySun228** [comment]
Hi @OmarAlJarrah this issue has been resolved, please use JsonNumericFieldPatternBuilder to mask any numeric data. 
The minimal version is 1.1.0
